const fs = require('node:fs');
const path = require('node:path');
const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Makes the "rest done" chime available to a notification channel in BOTH
 * debug and release builds.
 *
 * WHY NOT METRO's `require('...wav')` + `sound: 'rest-ding.wav'`? In a release
 * build Metro compiles bundled audio into an Android *resource*, and an
 * `expo-audio`/`SoundResolver` lookup by name (`R.raw.rest_ding`) cannot see it
 * — the asset was never registered as a notification sound resource. The result
 * is exactly the "times up" bubble with no sound this file exists to fix. The
 * same trap is recorded in docs/ARCHITECTURE.md for the bundled exercise clips.
 *
 * A `res/raw/` resource IS visible to `SoundResolver` (it resolves `rest-ding`
 * via `R.raw.rest_ding`, with @sfourdrinier's `SoundResolver.resourceExists`
 * falling back to the default only when the resource is absent). This plugin
 * copies `assets/rest-ding.wav` into `android/app/src/main/res/raw/` so the
 * default source set picks it up, and keeps wav files uncompressed.
 *
 * This lives in a config plugin because `android/` is generated by
 * `expo prebuild` and is gitignored: dropping the file in by hand would be
 * silently reverted on any fresh clone or prebuild. A duplicated entry is
 * harmless (the copy is idempotent), so no marker guard is needed.
 */
/**
 * Resource basename. Resource filenames may only contain `[a-z0-9_]`, so the
 * hyphens in `assets/rest-ding.wav` are rewritten to underscores here. This
 * is also the value JS passes as the channel/notification sound.
 */
const SOUND_RESOURCE = 'rest_ding.wav';

/** Source file in the project's assets/ directory. */
const SOUND_SOURCE = 'rest-ding.wav';

/** Guard so the `noCompress 'wav'` aaptOptions block is not appended twice. */
const MARKER = '// withNotificationSound: rest-done chime as a raw resource';

module.exports = function withNotificationSound(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `withNotificationSound expects a Groovy app/build.gradle, got ${cfg.modResults.language}.`,
      );
    }

    // Copy the chime into the default res/raw resource directory. Idempotent.
    const appDir = path.join(cfg.modRequest.platformProjectRoot, 'app');
    const resRaw = path.join(appDir, 'src', 'main', 'res', 'raw');
    fs.mkdirSync(resRaw, { recursive: true });
    fs.copyFileSync(
      path.join(cfg.modRequest.projectRoot, 'assets', SOUND_SOURCE),
      path.join(resRaw, SOUND_RESOURCE),
    );

    if (cfg.modResults.contents.includes(MARKER)) return cfg;

    cfg.modResults.contents += `
${MARKER}
//
// Appended by plugins/withNotificationSound.js — do not edit here, android/ is
// regenerated by \`expo prebuild\`.
android {
    androidResources {
        noCompress 'wav'
    }
}
`;
    return cfg;
  });
};