const fs = require('node:fs');
const path = require('node:path');
const {
  withAndroidManifest,
  withDangerousMod,
  withMainApplication,
} = require('@expo/config-plugins');

/**
 * Makes the workout keep-alive native module part of a fresh Android build.
 *
 * WHY A PLUGIN? The native half of the background-recording fix is three
 * Kotlin files (module + package + foreground service) plus a `MainApplication`
 * registration and an `AndroidManifest` service declaration. `android/` is
 * generated by `expo prebuild` and is gitignored, so any hand-edited file there
 * is silently reverted on a fresh clone or prebuild — exactly the trap
 * documented in plugins/withNotificationSound.js.
 *
 * The canonical sources live in the tracked `android-src/` directory; this
 * plugin copies them into the generated project and wires up the registration
 * and manifest entries. All steps are idempotent (marker-guarded).
 */

/** Relative (from the android project root) package dir the module lives in. */
const JAVA_PKG_DIR = path.join(
  'app',
  'src',
  'main',
  'java',
  'com',
  'ironlog',
  'app',
);

/** Kotlin files reproduced into the generated project on every prebuild. */
const KOTLIN_FILES = [
  'WorkoutKeepAliveModule.kt',
  'WorkoutKeepAlivePackage.kt',
  'WorkoutForegroundService.kt',
];

/** Marker guarding the MainApplication registration against double-injection. */
const MAIN_APP_MARKER = 'withWorkoutKeepAlive: package registration';

/** Permissions the foreground service needs (idempotent merge). */
const FOREGROUND_SERVICE_PERMISSIONS = [
  'android.permission.FOREGROUND_SERVICE',
  'android.permission.FOREGROUND_SERVICE_DATA_SYNC',
];

/** The service entry added to the application node (idempotent merge). */
const FOREGROUND_SERVICE_ELEMENT = {
  $: {
    'android:name': '.WorkoutForegroundService',
    'android:exported': 'false',
    'android:foregroundServiceType': 'dataSync',
    'android:stopWithTask': 'false',
  },
};

module.exports = function withWorkoutKeepAlive(config) {
  config = withMainApplication(config, (cfg) => {
    let contents = cfg.modResults.contents;
    if (contents.includes(MAIN_APP_MARKER)) return cfg;

    // The template can reference ReactPackage without importing it; make the
    // explicit import available only if the generated file lacks it.
    if (!contents.includes('import com.facebook.react.ReactPackage')) {
      contents = contents.replace(
        /import com\.facebook\.react\.(.*)$/m,
        'import com.facebook.react.ReactPackage\nimport com.facebook.react.$1',
      );
    }

    contents = contents.replace(
      '// Packages that cannot be autolinked yet can be added manually here, for example:',
      `// Packages that cannot be autolinked yet can be added manually here, for example:\n          // ${MAIN_APP_MARKER}\n          add(WorkoutKeepAlivePackage())`,
    );

    cfg.modResults.contents = contents;
    return cfg;
  });

  config = withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;

    const permissions = manifest['uses-permission'] ?? [];
    const seen = new Set(permissions.map((p) => p.$['android:name']));
    for (const name of FOREGROUND_SERVICE_PERMISSIONS) {
      if (!seen.has(name)) {
        permissions.push({ $: { 'android:name': name } });
      }
    }
    manifest['uses-permission'] = permissions;

    const application = manifest['application']?.[0];
    if (application !== undefined) {
      const services = application['service'] ?? [];
      const alreadyDeclared = services.some(
        (s) => s.$['android:name'] === FOREGROUND_SERVICE_ELEMENT.$['android:name'],
      );
      if (!alreadyDeclared) {
        services.push(FOREGROUND_SERVICE_ELEMENT);
        application['service'] = services;
      }
    }

    return cfg;
  });

  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const androidRoot = cfg.modRequest.platformProjectRoot;
      const sourceDir = path.join(
        projectRoot,
        'android-src',
        'src',
        'main',
        'java',
        'com',
        'ironlog',
        'app',
      );
      const destDir = path.join(androidRoot, JAVA_PKG_DIR);
      fs.mkdirSync(destDir, { recursive: true });
      for (const file of KOTLIN_FILES) {
        fs.copyFileSync(path.join(sourceDir, file), path.join(destDir, file));
      }
      return cfg;
    },
  ]);

  return config;
};