const fs = require('node:fs');
const path = require('node:path');
const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Packages the 1069 exercise demonstration clips as RAW Android assets.
 *
 * WHY NOT METRO? Metro compiles bundled assets into Android *resources*, and in
 * a release build a resource has no readable file path — `expo-asset` hands back
 * a bare resource name. That is the exact trap recorded in docs/ARCHITECTURE.md
 * ("bundled non-image assets are unreadable in release builds"), and it fails
 * only in production. Raw assets
 * keep a real path: `file:///android_asset/exercises/<slug>.mp4`, which media3
 * routes to its `AssetDataSource` (verified in `DefaultDataSource.open`, which
 * dispatches on `uri.getPath().startsWith("/android_asset/")`).
 *
 * The tree comes from `<projectRoot>/media`, built by `npm run media:stage` as
 * hard links into `exercises_db/`. Staging is NOT run from here: it needs `tsx`
 * (a devDependency) and the 3.7 GB source tree, neither of which is guaranteed
 * on a build machine, and a prebuild that dies inside a dangerous mod is an
 * opaque failure. Instead this warns loudly when the tree is missing.
 *
 * This lives in a config plugin because `android/` is generated by
 * `expo prebuild` and is gitignored: editing app/build.gradle directly would be
 * silently reverted on any fresh clone or prebuild. Same reason as
 * plugins/withGradleMemory.js.
 */

/** Staging dir, relative to the project root. Must match scripts/stage-media.ts. */
const MEDIA_DIR = 'media';

/**
 * Guard so a re-run — or a duplicated plugin entry — cannot append the block
 * twice. Gradle would tolerate the duplicate, but the file would rot.
 */
const MARKER = '// withExerciseMedia: bundled exercise demonstration clips';

/**
 * Both calls are the ADDITIVE forms, and both are declared on the AGP 8.x public
 * DSL interfaces (checked against AGP 8.12.0, the version this project resolves):
 *
 * - `AndroidSourceDirectorySet.srcDir(Object)` appends. `srcDirs += [...]` would
 *   need a `getSrcDirs()` that only the legacy impl class carries, not the
 *   interface.
 * - `AndroidResources.noCompress(String...)` appends. `noCompress += [...]` is
 *   wrong here: the interface declares a getter and no setter. `aaptOptions` is
 *   the AGP 7 name for the same block and is gone.
 *
 * `noCompress 'mp4'` is a requirement, not an optimisation. `AssetDataSource`
 * reads with `AssetManager.open(path, ACCESS_RANDOM)` and seeks by calling
 * `InputStream.skip()`, which on a DEFLATEd entry re-inflates from byte zero
 * every time. H.264-in-MP4 is already compressed, so storing it costs nothing
 * and buys cheap random access.
 */
function gradleBlock(relativeMediaDir) {
  return `
${MARKER}
//
// Appended by plugins/withExerciseMedia.js — do not edit here, android/ is
// regenerated by \`expo prebuild\`. Populate the tree with \`npm run media:stage\`.
android {
    sourceSets {
        main {
            assets.srcDir '${relativeMediaDir}'
        }
    }
    androidResources {
        noCompress 'mp4'
    }
}
`;
}

function warnIfUnstaged(mediaDir) {
  const exercisesDir = path.join(mediaDir, 'exercises');
  let count;
  try {
    count = fs.readdirSync(exercisesDir).length;
  } catch {
    count = 0;
  }
  if (count === 0) {
    console.warn(
      `withExerciseMedia: ${exercisesDir} is empty or missing, so the APK will ` +
        'ship with no exercise clips and every ExerciseVideo will render its ' +
        'fallback. Run `npm run media:stage` before building.',
    );
  }
}

module.exports = function withExerciseMedia(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `withExerciseMedia expects a Groovy app/build.gradle, got ${cfg.modResults.language}.`,
      );
    }
    if (cfg.modResults.contents.includes(MARKER)) return cfg;

    const mediaDir = path.join(cfg.modRequest.projectRoot, MEDIA_DIR);
    warnIfUnstaged(mediaDir);

    // Gradle resolves a relative srcDir against the :app project dir. A relative
    // path keeps the generated file machine-independent, which matters because
    // CI and a developer clone do not share an absolute project path.
    const appDir = path.join(cfg.modRequest.platformProjectRoot, 'app');
    const relative = path.relative(appDir, mediaDir).split(path.sep).join('/');

    cfg.modResults.contents += gradleBlock(relative);
    return cfg;
  });
};
