const { withGradleProperties } = require('@expo/config-plugins');

/**
 * Raises the Gradle JVM heap.
 *
 * The default is 2 GB, and dex-merging this dependency set (Skia, Reanimated,
 * Screens and the Expo modules) exhausts it. The failure is opaque — AGP
 * reports `DexArchiveMergerException` with an EMPTY message rather than an
 * out-of-memory error — so it reads as a mysterious build break.
 *
 * This lives in a config plugin because `android/` is generated by
 * `expo prebuild` and is gitignored: editing gradle.properties directly would
 * be silently reverted on any fresh clone or prebuild. `expo-build-properties`
 * covers most gradle.properties keys but not `org.gradle.jvmargs`.
 */
const JVM_ARGS = '-Xmx6144m -XX:MaxMetaspaceSize=1024m';

module.exports = function withGradleMemory(config) {
  return withGradleProperties(config, (cfg) => {
    const properties = cfg.modResults.filter(
      (item) => !(item.type === 'property' && item.key === 'org.gradle.jvmargs'),
    );

    properties.push({
      type: 'comment',
      value:
        'Raised from the 2 GB default: dex-merging this dependency set OOMs the ' +
        'merger, which surfaces as an empty-message DexArchiveMergerException. ' +
        'Set by plugins/withGradleMemory.js.',
    });
    properties.push({
      type: 'property',
      key: 'org.gradle.jvmargs',
      value: JVM_ARGS,
    });

    cfg.modResults = properties;
    return cfg;
  });
};
