/**
 * Generates the bundled exercise artwork as TypeScript string modules.
 *
 * WHY NOT `require()` THE .svg FILES?
 * That was the first approach and it fails in release builds. Metro assets are
 * compiled into Android *resources*, so `Asset.fromModule(...)` resolves to a
 * bare resource NAME (e.g. "assets_art_abrollout1"), not a path. expo-asset
 * then reports `downloaded: true` and never copies the file, and
 * `new File(uri).text()` throws `IllegalArgumentException: URI is not absolute`.
 * It works in development (Metro serves an http URL) and silently falls back to
 * the muscle map in production — the worst possible failure shape.
 *
 * WHY NOT react-native-svg-transformer (SVG -> JSX at build time)?
 * It is the idiomatic RN answer, but it re-expresses the artwork as JSX props,
 * so the shipped binary no longer contains the original bytes. Byte-identity is
 * the foundation of the licensing position in docs/ART_LICENSING.md, and it is
 * unarguable in a way that "format-shifting is permitted" is not.
 *
 * SO: the exact file bytes are embedded as JS string literals via
 * `JSON.stringify`, which is lossless. The artwork is still distributed
 * verbatim — the same bytes in a different container, like a file inside a ZIP —
 * and `art.test.ts` asserts each embedded string equals its source file exactly.
 *
 * Output is chunked so no single module is enormous, which keeps Babel and
 * Metro comfortable. Hermes keeps string literals in its bytecode string table
 * and materialises them on access, so this costs bundle size rather than
 * start-up time.
 *
 * Run via `npm run art:registry` (the harvest does it automatically).
 */
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { Manifest } from './harvest-art';

const ROOT = path.join(__dirname, '..');
const ART_DIR = path.join(ROOT, 'assets', 'art');
const MANIFEST = path.join(ART_DIR, 'manifest.json');
const OUT_DIR = path.join(ROOT, 'src', 'data', 'art');

/** Roughly how many exercises per generated chunk. */
const CHUNK_SIZE = 20;

const HEADER = [
  '/**',
  ' * AUTO-GENERATED by scripts/build-art-registry.ts — do not edit.',
  ' *',
  ' * Exercise illustrations by Everkinetic, CC BY-SA 3.0, embedded VERBATIM.',
  ' * Each string is the exact byte content of the corresponding file in',
  ' * assets/art/. Do not reformat, minify or "clean up" these strings: see',
  ' * docs/ART_LICENSING.md. Regenerate with `npm run art:registry`.',
  ' */',
  '',
].join('\n');

export async function buildRegistry(): Promise<number> {
  const manifest = JSON.parse(await readFile(MANIFEST, 'utf8')) as Manifest;

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const entries = [...manifest.entries].sort((a, b) =>
    a.exerciseSlug.localeCompare(b.exerciseSlug),
  );

  const chunkNames: string[] = [];
  let count = 0;

  for (let i = 0; i < entries.length; i += CHUNK_SIZE) {
    const slice = entries.slice(i, i + CHUNK_SIZE);
    const chunkIndex = Math.floor(i / CHUNK_SIZE);
    const chunkName = `chunk${String(chunkIndex).padStart(2, '0')}`;
    chunkNames.push(chunkName);

    const lines: string[] = [HEADER, 'export const ART: Record<string, string[]> = {'];

    for (const entry of slice) {
      const frames = [...entry.frames].sort((a, b) => a.frame - b.frame);
      const svgs: string[] = [];
      for (const f of frames) {
        svgs.push(await readFile(path.join(ART_DIR, f.file), 'utf8'));
      }
      lines.push(`  ${JSON.stringify(entry.exerciseSlug)}: [`);
      for (const svg of svgs) lines.push(`    ${JSON.stringify(svg)},`);
      lines.push('  ],');
      count += 1;
    }

    lines.push('};', '');
    await writeFile(path.join(OUT_DIR, `${chunkName}.ts`), lines.join('\n'));
  }

  // Dimensions live in the index rather than the chunks: the UI needs the
  // aspect ratio to lay out a placeholder BEFORE touching the markup, and the
  // ratios are genuinely not uniform (1120x1200 portrait vs 1200x858 landscape).
  const dims: string[] = [];
  for (const e of entries) {
    const first = [...e.frames].sort((a, b) => a.frame - b.frame)[0];
    if (first === undefined) continue;
    dims.push(
      `  ${JSON.stringify(e.exerciseSlug)}: { width: ${first.width}, height: ${first.height}, frames: ${e.frames.length} },`,
    );
  }

  const index = [
    HEADER,
    ...chunkNames.map((c, i) => `import { ART as ART_${i} } from './${c}';`),
    '',
    'export interface ArtMeta {',
    '  readonly width: number;',
    '  readonly height: number;',
    '  readonly frames: number;',
    '}',
    '',
    '/** Aspect ratios, so a placeholder can be sized before parsing any markup. */',
    'export const ART_META: Record<string, ArtMeta> = {',
    ...dims,
    '};',
    '',
    '/** slug -> [frame 1 svg, frame 2 svg]. Byte-identical to assets/art/. */',
    'const CHUNKS: Record<string, string[]>[] = [',
    ...chunkNames.map((_, i) => `  ART_${i},`),
    '];',
    '',
    'const INDEX: Record<string, string[]> = Object.assign({}, ...CHUNKS);',
    '',
    'export function artFrames(slug: string | null | undefined): string[] | null {',
    '  if (slug == null) return null;',
    '  return INDEX[slug] ?? null;',
    '}',
    '',
    'export function artMeta(slug: string | null | undefined): ArtMeta | null {',
    '  if (slug == null) return null;',
    '  return ART_META[slug] ?? null;',
    '}',
    '',
    'export function hasArt(slug: string | null | undefined): boolean {',
    '  return slug != null && slug in INDEX;',
    '}',
    '',
    '/** Every slug with bundled artwork. */',
    'export function artSlugs(): string[] {',
    '  return Object.keys(INDEX);',
    '}',
    '',
  ].join('\n');

  await writeFile(path.join(OUT_DIR, 'index.ts'), index);

  // Remove the old require()-based registry if it is still lying around.
  const stale = path.join(ROOT, 'src', 'data', 'artRegistry.ts');
  await rm(stale, { force: true });

  const written = await readdir(OUT_DIR);
  console.log(`  ${written.length} modules in src/data/art/`);
  return count;
}

if (require.main === module) {
  buildRegistry()
    .then((n) => console.log(`wrote artwork for ${n} exercises`))
    .catch((err: unknown) => {
      console.error(err instanceof Error ? err.message : String(err));
      process.exit(1);
    });
}
