/**
 * Turns the 1069 identical-but-differently-shaded `target_muscles.svg` files
 * into ONE tokenised template.
 *
 * Every source file is the same 54 KB drawing; only the 81 `fill` attributes
 * differ (see src/data/muscleArt/regions.ts). This script asserts that — all
 * files must be byte-identical once fills are stripped — and then emits the
 * template with `fill="@<pathIndex>@"` placeholders for the renderer to fill.
 *
 * Run with `npm run art:template`.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PATH_COUNT } from '../src/data/muscleArt/regions';

const DB = join(__dirname, '..', 'exercises_db');
const OUT = join(__dirname, '..', 'src', 'data', 'muscleArt', 'template.ts');
const FILL = /fill="#[0-9a-fA-F]{6}"/g;

function stripped(svg: string): string {
  return svg.replace(FILL, 'fill="@"');
}

const slugs = readdirSync(DB).sort();
let canonical: string | null = null;
let canonicalSlug = '';

for (const slug of slugs) {
  const svg = readFileSync(join(DB, slug, 'target_muscles.svg'), 'utf8');
  const bare = stripped(svg);
  if (canonical === null) {
    canonical = bare;
    canonicalSlug = slug;
  } else if (bare !== canonical) {
    throw new Error(
      `${slug}/target_muscles.svg differs from ${canonicalSlug} outside its ` +
        `fill attributes, so a single shared template cannot represent it.`,
    );
  }
  const fills = svg.match(FILL) ?? [];
  if (fills.length !== PATH_COUNT) {
    throw new Error(
      `${slug}/target_muscles.svg has ${fills.length} fills, expected ${PATH_COUNT}.`,
    );
  }
}

if (canonical === null) throw new Error(`No SVGs found under ${DB}.`);

// Re-inject placeholders, numbered by path index.
let index = 0;
const template = canonical.replace(/fill="@"/g, () => `fill="@${index++}@"`);
if (index !== PATH_COUNT) {
  throw new Error(`Tokenised ${index} fills, expected ${PATH_COUNT}.`);
}

const viewBox = /viewBox="([^"]+)"/.exec(template)?.[1];
if (viewBox === undefined) throw new Error('Template has no viewBox.');
const bounds = viewBox.split(/\s+/).map(Number);
const w = bounds[2];
const h = bounds[3];
if (w === undefined || h === undefined || !Number.isFinite(w) || !Number.isFinite(h)) {
  throw new Error(`Template viewBox "${viewBox}" has no usable width/height.`);
}

const digest = createHash('sha256').update(canonical).digest('hex').slice(0, 16);

writeFileSync(
  OUT,
  `/**
 * AUTO-GENERATED by scripts/build-muscle-template.ts — do not edit.
 *
 * The muscle-worked drawing shared by all ${slugs.length} exercises, with each of its
 * ${PATH_COUNT} \`fill\` attributes replaced by an \`@<pathIndex>@\` placeholder. The
 * renderer substitutes theme colours per path; see src/components/MuscleMap.tsx.
 *
 * Front figure occupies x 0..${w / 2}, back figure x ${w / 2}..${w}.
 * Source fingerprint (fills stripped): ${digest}
 */

/** Placeholder-bearing SVG. Substitute \`@N@\` for every path index. */
export const MUSCLE_ART_TEMPLATE =
  ${JSON.stringify(template)};

export const TEMPLATE_VIEWBOX = ${JSON.stringify(viewBox)};
export const TEMPLATE_WIDTH = ${w};
export const TEMPLATE_HEIGHT = ${h};
/** The front figure alone, for thumbnails. */
export const FRONT_VIEWBOX = ${JSON.stringify(`0 0 ${w / 2} ${h}`)};
/** The back figure alone. */
export const BACK_VIEWBOX = ${JSON.stringify(`${w / 2} 0 ${w / 2} ${h}`)};
`,
  'utf8',
);

console.log(
  `template.ts written from ${slugs.length} files (${(template.length / 1024).toFixed(1)} KB, ${PATH_COUNT} tokens)`,
);
