/**
 * AUTO-GENERATED by scripts/build-art-registry.ts — do not edit.
 *
 * Exercise illustrations by Everkinetic, CC BY-SA 3.0, embedded VERBATIM.
 * Each string is the exact byte content of the corresponding file in
 * assets/art/. Do not reformat, minify or "clean up" these strings: see
 * docs/ART_LICENSING.md. Regenerate with `npm run art:registry`.
 */

import { ART as ART_0 } from './chunk00';
import { ART as ART_1 } from './chunk01';
import { ART as ART_2 } from './chunk02';
import { ART as ART_3 } from './chunk03';
import { ART as ART_4 } from './chunk04';
import { ART as ART_5 } from './chunk05';
import { ART as ART_6 } from './chunk06';
import { ART as ART_7 } from './chunk07';
import { ART as ART_8 } from './chunk08';

export interface ArtMeta {
  readonly width: number;
  readonly height: number;
  readonly frames: number;
}

/** Aspect ratios, so a placeholder can be sized before parsing any markup. */
export const ART_META: Record<string, ArtMeta> = {
  "ab-rollout": { width: 1200, height: 858, frames: 2 },
  "arnold-press": { width: 661, height: 1200, frames: 2 },
  "back-extension": { width: 1020, height: 1200, frames: 2 },
  "back-extension-stability-ball": { width: 1200, height: 790, frames: 2 },
  "barbell-pullover": { width: 1200, height: 898, frames: 2 },
  "behind-the-neck-press": { width: 1200, height: 976, frames: 2 },
  "bench-dip": { width: 1200, height: 894, frames: 2 },
  "bench-press-barbell": { width: 1120, height: 1200, frames: 2 },
  "bench-press-dumbbell": { width: 860, height: 1200, frames: 2 },
  "bench-press-machine": { width: 1024, height: 1200, frames: 2 },
  "bench-press-smith-machine": { width: 1048, height: 1200, frames: 2 },
  "bent-over-row-underhand": { width: 1131, height: 1200, frames: 2 },
  "biceps-curl-alternating-dumbbell": { width: 651, height: 1200, frames: 2 },
  "biceps-curl-barbell": { width: 1200, height: 1106, frames: 2 },
  "biceps-curl-cable": { width: 555, height: 1200, frames: 2 },
  "biceps-curl-dumbbell": { width: 645, height: 1200, frames: 2 },
  "biceps-curl-machine": { width: 970, height: 1200, frames: 2 },
  "bicycle-crunch": { width: 1200, height: 506, frames: 2 },
  "box-squat-barbell": { width: 996, height: 1200, frames: 2 },
  "cable-crossover": { width: 1030, height: 1200, frames: 2 },
  "cable-crunch": { width: 559, height: 1200, frames: 2 },
  "cable-fly-flat-bench": { width: 1153, height: 1200, frames: 2 },
  "cable-fly-incline": { width: 1159, height: 1200, frames: 2 },
  "calf-press-leg-machine": { width: 1200, height: 819, frames: 2 },
  "calf-raise-seated-barbell": { width: 806, height: 1200, frames: 2 },
  "calf-raise-seated-machine": { width: 826, height: 1200, frames: 2 },
  "calf-raise-single-leg-dumbbell": { width: 923, height: 1200, frames: 2 },
  "calf-raise-standing-barbell": { width: 1200, height: 1018, frames: 2 },
  "calf-raise-standing-machine": { width: 943, height: 1200, frames: 2 },
  "chest-dip": { width: 659, height: 1200, frames: 2 },
  "chest-fly-dumbbell": { width: 998, height: 1200, frames: 2 },
  "chest-press-one-arm": { width: 788, height: 1200, frames: 2 },
  "chin-up": { width: 758, height: 1200, frames: 2 },
  "close-grip-bench-press": { width: 1200, height: 1180, frames: 2 },
  "close-grip-curl-barbell": { width: 1200, height: 1106, frames: 2 },
  "close-grip-ez-bar-curl": { width: 1135, height: 1200, frames: 2 },
  "close-grip-push-up": { width: 1200, height: 614, frames: 2 },
  "concentration-curl": { width: 748, height: 1200, frames: 2 },
  "cross-body-crunch": { width: 1200, height: 575, frames: 2 },
  "cross-body-hammer-curl": { width: 575, height: 1200, frames: 2 },
  "crunch": { width: 1200, height: 531, frames: 2 },
  "cuban-press": { width: 1200, height: 1195, frames: 2 },
  "deadlift-barbell": { width: 820, height: 1200, frames: 2 },
  "deadlift-dumbbell": { width: 570, height: 1200, frames: 2 },
  "deadlift-smith-machine": { width: 729, height: 1200, frames: 2 },
  "decline-barbell-pullover": { width: 1200, height: 991, frames: 2 },
  "decline-bench-press-barbell": { width: 1200, height: 994, frames: 2 },
  "decline-bench-press-dumbbell": { width: 1200, height: 1126, frames: 2 },
  "decline-chest-fly-dumbbell": { width: 1200, height: 921, frames: 2 },
  "decline-chest-press-machine": { width: 948, height: 1200, frames: 2 },
  "decline-crunch": { width: 1200, height: 1015, frames: 2 },
  "decline-oblique-crunch": { width: 1200, height: 1051, frames: 2 },
  "decline-skull-crusher": { width: 1200, height: 1041, frames: 2 },
  "donkey-calf-raise": { width: 916, height: 1200, frames: 2 },
  "drag-curl": { width: 1048, height: 1200, frames: 2 },
  "dumbbell-pullover": { width: 1200, height: 1040, frames: 2 },
  "exercise-ball-pull-in": { width: 1200, height: 609, frames: 2 },
  "external-rotation-cable": { width: 1166, height: 1200, frames: 2 },
  "ez-bar-curl": { width: 1135, height: 1200, frames: 2 },
  "floor-press": { width: 1200, height: 605, frames: 2 },
  "flutter-kick": { width: 1200, height: 478, frames: 2 },
  "front-raise-barbell": { width: 853, height: 1200, frames: 2 },
  "front-raise-cable": { width: 583, height: 1200, frames: 2 },
  "front-raise-dumbbell": { width: 469, height: 1200, frames: 2 },
  "front-squat-barbell": { width: 991, height: 1200, frames: 2 },
  "glute-bridge": { width: 1200, height: 593, frames: 2 },
  "good-morning-barbell": { width: 1006, height: 1200, frames: 2 },
  "good-morning-smith-machine": { width: 999, height: 1200, frames: 2 },
  "hack-squat-barbell": { width: 993, height: 1200, frames: 2 },
  "hack-squat-machine": { width: 893, height: 1200, frames: 2 },
  "hammer-curl-alternating": { width: 573, height: 1200, frames: 2 },
  "hammer-curl-dumbbell": { width: 645, height: 1200, frames: 2 },
  "hammer-curl-rope-cable": { width: 474, height: 1200, frames: 2 },
  "high-cable-curl": { width: 930, height: 1200, frames: 2 },
  "hip-abduction-machine": { width: 973, height: 1200, frames: 1 },
  "hip-adduction-machine": { width: 744, height: 1200, frames: 2 },
  "hip-raise-bent-knee": { width: 1200, height: 1030, frames: 2 },
  "incline-bench-press-barbell": { width: 1023, height: 1200, frames: 2 },
  "incline-bench-press-dumbbell": { width: 819, height: 1200, frames: 2 },
  "incline-chest-fly-dumbbell": { width: 941, height: 1200, frames: 2 },
  "incline-chest-press-machine": { width: 889, height: 1200, frames: 2 },
  "incline-curl-dumbbell": { width: 840, height: 1200, frames: 2 },
  "incline-shoulder-press-dumbbell": { width: 789, height: 1200, frames: 2 },
  "incline-triceps-extension-dumbbell": { width: 985, height: 1200, frames: 2 },
  "inverted-row": { width: 1079, height: 1200, frames: 2 },
  "iron-cross": { width: 1098, height: 1200, frames: 2 },
  "jefferson-squat": { width: 485, height: 1200, frames: 2 },
  "jm-press": { width: 1200, height: 1154, frames: 2 },
  "lat-pulldown-underhand": { width: 479, height: 1200, frames: 2 },
  "lat-pulldown-v-bar": { width: 475, height: 1200, frames: 2 },
  "lat-pulldown-wide": { width: 793, height: 1200, frames: 2 },
  "lateral-raise-dumbbell": { width: 1079, height: 1200, frames: 2 },
  "leg-curl-lying": { width: 1200, height: 684, frames: 2 },
  "leg-curl-seated": { width: 800, height: 1200, frames: 2 },
  "leg-curl-standing": { width: 853, height: 1200, frames: 2 },
  "leg-extension": { width: 788, height: 1200, frames: 2 },
  "lunge-barbell": { width: 1121, height: 1200, frames: 1 },
  "lunge-walking": { width: 831, height: 1200, frames: 2 },
  "lying-cable-curl": { width: 1200, height: 584, frames: 2 },
  "lying-leg-raise": { width: 1200, height: 829, frames: 2 },
  "lying-rear-lateral-raise": { width: 1200, height: 830, frames: 2 },
  "lying-triceps-extension-cable": { width: 1200, height: 1068, frames: 2 },
  "lying-triceps-extension-dumbbell": { width: 1200, height: 1128, frames: 2 },
  "lying-triceps-press-barbell": { width: 1200, height: 1049, frames: 2 },
  "narrow-stance-squat-barbell": { width: 998, height: 1200, frames: 1 },
  "neck-flexion-extension": { width: 1140, height: 1200, frames: 2 },
  "neck-side-flexion": { width: 1070, height: 1200, frames: 2 },
  "neutral-grip-pull-up": { width: 710, height: 1200, frames: 2 },
  "one-arm-snatch-barbell": { width: 750, height: 1200, frames: 2 },
  "overhead-curl-cable": { width: 1170, height: 1200, frames: 2 },
  "overhead-press-barbell": { width: 896, height: 1200, frames: 2 },
  "overhead-squat": { width: 1200, height: 1039, frames: 2 },
  "overhead-triceps-extension-barbell": { width: 855, height: 1200, frames: 2 },
  "overhead-triceps-extension-cable": { width: 749, height: 1200, frames: 2 },
  "overhead-triceps-extension-dumbbell": { width: 449, height: 1200, frames: 2 },
  "overhead-triceps-extension-seated-barbell": { width: 941, height: 1200, frames: 2 },
  "pec-deck": { width: 824, height: 1200, frames: 2 },
  "pile-squat": { width: 699, height: 1200, frames: 2 },
  "pistol-squat": { width: 1115, height: 1200, frames: 2 },
  "plate-curl": { width: 545, height: 1200, frames: 2 },
  "preacher-curl-barbell": { width: 868, height: 1200, frames: 2 },
  "preacher-curl-cable": { width: 676, height: 1200, frames: 2 },
  "preacher-curl-dumbbell": { width: 740, height: 1200, frames: 2 },
  "preacher-curl-machine": { width: 793, height: 1200, frames: 2 },
  "pull-up": { width: 794, height: 1200, frames: 2 },
  "push-up": { width: 1200, height: 669, frames: 2 },
  "push-up-feet-elevated": { width: 1200, height: 838, frames: 2 },
  "rear-delt-fly-cable": { width: 1129, height: 1200, frames: 2 },
  "rear-delt-fly-dumbbell": { width: 1189, height: 1200, frames: 2 },
  "rear-delt-fly-seated-cable": { width: 1200, height: 949, frames: 2 },
  "rear-delt-row-barbell": { width: 1136, height: 1200, frames: 2 },
  "rear-delt-row-dumbbell": { width: 1100, height: 1200, frames: 2 },
  "reverse-curl-dumbbell": { width: 575, height: 1200, frames: 2 },
  "reverse-grip-bench-press": { width: 1030, height: 1200, frames: 2 },
  "reverse-lunge-barbell": { width: 1121, height: 1200, frames: 1 },
  "romanian-deadlift-barbell": { width: 824, height: 1200, frames: 2 },
  "seated-cable-row": { width: 1200, height: 814, frames: 2 },
  "seated-curl-dumbbell": { width: 913, height: 1200, frames: 1 },
  "seated-military-press": { width: 919, height: 1200, frames: 2 },
  "shoulder-press-dumbbell": { width: 724, height: 1200, frames: 2 },
  "shoulder-press-machine": { width: 825, height: 1200, frames: 2 },
  "shoulder-press-one-arm-dumbbell": { width: 544, height: 1200, frames: 2 },
  "shrug-barbell": { width: 810, height: 1200, frames: 2 },
  "shrug-cable": { width: 498, height: 1200, frames: 2 },
  "shrug-dumbbell": { width: 543, height: 1200, frames: 2 },
  "shrug-smith-machine": { width: 963, height: 1200, frames: 2 },
  "side-bend-dumbbell": { width: 531, height: 1200, frames: 2 },
  "side-plank": { width: 1200, height: 554, frames: 2 },
  "single-leg-squat-barbell": { width: 998, height: 1200, frames: 2 },
  "sissy-squat": { width: 661, height: 1200, frames: 2 },
  "skull-crusher-barbell": { width: 1200, height: 768, frames: 2 },
  "spider-curl": { width: 878, height: 1200, frames: 2 },
  "squat-dumbbell": { width: 509, height: 1200, frames: 2 },
  "squat-smith-machine": { width: 899, height: 1200, frames: 2 },
  "stability-ball-crunch": { width: 1200, height: 936, frames: 2 },
  "step-up-barbell": { width: 886, height: 1200, frames: 2 },
  "step-up-dumbbell": { width: 649, height: 1200, frames: 2 },
  "stomach-vacuum": { width: 1200, height: 650, frames: 2 },
  "straight-arm-pulldown": { width: 490, height: 1200, frames: 2 },
  "superman": { width: 1200, height: 266, frames: 2 },
  "t-bar-row": { width: 1114, height: 1200, frames: 2 },
  "triceps-dip": { width: 658, height: 1200, frames: 2 },
  "triceps-extension-machine": { width: 753, height: 1200, frames: 2 },
  "triceps-kickback-cable": { width: 796, height: 1200, frames: 2 },
  "triceps-kickback-dumbbell": { width: 1078, height: 1200, frames: 2 },
  "triceps-pushdown-cable": { width: 424, height: 1200, frames: 2 },
  "triceps-pushdown-reverse-grip": { width: 449, height: 1200, frames: 2 },
  "triceps-pushdown-rope": { width: 425, height: 1200, frames: 2 },
  "triceps-pushdown-v-bar": { width: 408, height: 1200, frames: 2 },
  "upright-row-barbell": { width: 1013, height: 1200, frames: 2 },
  "upright-row-cable": { width: 620, height: 1200, frames: 2 },
  "upright-row-dumbbell": { width: 619, height: 1200, frames: 2 },
  "upright-row-smith-machine": { width: 961, height: 1200, frames: 2 },
  "wide-grip-bench-press": { width: 1200, height: 1078, frames: 2 },
  "wide-grip-chin-up": { width: 935, height: 1200, frames: 2 },
  "wide-grip-curl-barbell": { width: 1200, height: 1106, frames: 2 },
  "wide-stance-squat-barbell": { width: 1200, height: 1006, frames: 2 },
  "zercher-squat": { width: 1200, height: 1064, frames: 2 },
  "zottman-curl": { width: 645, height: 1200, frames: 2 },
};

/** slug -> [frame 1 svg, frame 2 svg]. Byte-identical to assets/art/. */
const CHUNKS: Record<string, string[]>[] = [
  ART_0,
  ART_1,
  ART_2,
  ART_3,
  ART_4,
  ART_5,
  ART_6,
  ART_7,
  ART_8,
];

const INDEX: Record<string, string[]> = Object.assign({}, ...CHUNKS);

export function artFrames(slug: string | null | undefined): string[] | null {
  if (slug == null) return null;
  return INDEX[slug] ?? null;
}

export function artMeta(slug: string | null | undefined): ArtMeta | null {
  if (slug == null) return null;
  return ART_META[slug] ?? null;
}

export function hasArt(slug: string | null | undefined): boolean {
  return slug != null && slug in INDEX;
}

/** Every slug with bundled artwork. */
export function artSlugs(): string[] {
  return Object.keys(INDEX);
}
