/**
 * AUTO-GENERATED by scripts/build-exercise-db.ts — do not edit.
 *
 * The bundled exercise catalogue, built from the source directories under
 * exercises_db/. Muscle lists and region maps are read off each exercise's
 * target_muscles.svg; prose comes from its details.txt. Regenerate with
 * `npx tsx scripts/build-exercise-db.ts`.
 */
import { EXERCISES as CHUNK_0 } from './chunk00';
import { EXERCISES as CHUNK_1 } from './chunk01';
import { EXERCISES as CHUNK_2 } from './chunk02';
import { EXERCISES as CHUNK_3 } from './chunk03';
import { EXERCISES as CHUNK_4 } from './chunk04';
import { EXERCISES as CHUNK_5 } from './chunk05';
import { EXERCISES as CHUNK_6 } from './chunk06';
import { EXERCISES as CHUNK_7 } from './chunk07';
import { EXERCISES as CHUNK_8 } from './chunk08';
import { EXERCISES as CHUNK_9 } from './chunk09';
import { EXERCISES as CHUNK_10 } from './chunk10';
import type { DbExercise } from './types';

export type { DbExercise, Mistake, RegionLevel, RegionMap } from './types';

/**
 * Every bundled exercise, sorted by name. The chunk files exist only to keep
 * individual modules small enough for Babel and Metro; they are already in
 * name order, so concatenating them needs no re-sort.
 */
export const ALL_EXERCISES: readonly DbExercise[] = [
  ...CHUNK_0,
  ...CHUNK_1,
  ...CHUNK_2,
  ...CHUNK_3,
  ...CHUNK_4,
  ...CHUNK_5,
  ...CHUNK_6,
  ...CHUNK_7,
  ...CHUNK_8,
  ...CHUNK_9,
  ...CHUNK_10,
];

/**
 * A Map, not an object literal: a plain object inherits Object.prototype, so
 * a lookup for "constructor" or "toString" would return an inherited function
 * typed as a DbExercise, and `?? null` does not catch it. No caller passes
 * anything but a real slug today, which is exactly why an unsound lookup here
 * would go unnoticed.
 */
const BY_SLUG = new Map<string, DbExercise>(ALL_EXERCISES.map((e) => [e.slug, e]));

/** Lookup by the directory name the exercise was generated from. */
export function exerciseBySlug(slug: string | null | undefined): DbExercise | null {
  if (slug == null) return null;
  return BY_SLUG.get(slug) ?? null;
}

/** Every catalogue slug, in name order. */
export function exerciseSlugs(): string[] {
  return ALL_EXERCISES.map((e) => e.slug);
}
